/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KundeRouteImport } from './routes/kunde'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as KundeRechnungenRouteImport } from './routes/kunde.rechnungen'
import { Route as KundeNeuerVorgangRouteImport } from './routes/kunde.neuer-vorgang'
import { Route as KundeLieferscheineRouteImport } from './routes/kunde.lieferscheine'
import { Route as KundeHistoryRouteImport } from './routes/kunde.history'
import { Route as AdminSitesRouteImport } from './routes/admin.sites'
import { Route as AdminRechnungenRouteImport } from './routes/admin.rechnungen'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminLieferscheineRouteImport } from './routes/admin.lieferscheine'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as KundeNeuerVorgangIndexRouteImport } from './routes/kunde.neuer-vorgang.index'
import { Route as KundeNeuerVorgangPickupRouteImport } from './routes/kunde.neuer-vorgang.pickup'
import { Route as KundeNeuerVorgangDropoffRouteImport } from './routes/kunde.neuer-vorgang.dropoff'

const KundeRoute = KundeRouteImport.update({
  id: '/kunde',
  path: '/kunde',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const KundeRechnungenRoute = KundeRechnungenRouteImport.update({
  id: '/rechnungen',
  path: '/rechnungen',
  getParentRoute: () => KundeRoute,
} as any)
const KundeNeuerVorgangRoute = KundeNeuerVorgangRouteImport.update({
  id: '/neuer-vorgang',
  path: '/neuer-vorgang',
  getParentRoute: () => KundeRoute,
} as any)
const KundeLieferscheineRoute = KundeLieferscheineRouteImport.update({
  id: '/lieferscheine',
  path: '/lieferscheine',
  getParentRoute: () => KundeRoute,
} as any)
const KundeHistoryRoute = KundeHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => KundeRoute,
} as any)
const AdminSitesRoute = AdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRechnungenRoute = AdminRechnungenRouteImport.update({
  id: '/rechnungen',
  path: '/rechnungen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLieferscheineRoute = AdminLieferscheineRouteImport.update({
  id: '/lieferscheine',
  path: '/lieferscheine',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const KundeNeuerVorgangIndexRoute = KundeNeuerVorgangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KundeNeuerVorgangRoute,
} as any)
const KundeNeuerVorgangPickupRoute = KundeNeuerVorgangPickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => KundeNeuerVorgangRoute,
} as any)
const KundeNeuerVorgangDropoffRoute =
  KundeNeuerVorgangDropoffRouteImport.update({
    id: '/dropoff',
    path: '/dropoff',
    getParentRoute: () => KundeNeuerVorgangRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kunde': typeof KundeRouteWithChildren
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/lieferscheine': typeof AdminLieferscheineRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/rechnungen': typeof AdminRechnungenRoute
  '/admin/sites': typeof AdminSitesRoute
  '/kunde/history': typeof KundeHistoryRoute
  '/kunde/lieferscheine': typeof KundeLieferscheineRoute
  '/kunde/neuer-vorgang': typeof KundeNeuerVorgangRouteWithChildren
  '/kunde/rechnungen': typeof KundeRechnungenRoute
  '/admin/': typeof AdminIndexRoute
  '/kunde/neuer-vorgang/dropoff': typeof KundeNeuerVorgangDropoffRoute
  '/kunde/neuer-vorgang/pickup': typeof KundeNeuerVorgangPickupRoute
  '/kunde/neuer-vorgang/': typeof KundeNeuerVorgangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kunde': typeof KundeRouteWithChildren
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/lieferscheine': typeof AdminLieferscheineRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/rechnungen': typeof AdminRechnungenRoute
  '/admin/sites': typeof AdminSitesRoute
  '/kunde/history': typeof KundeHistoryRoute
  '/kunde/lieferscheine': typeof KundeLieferscheineRoute
  '/kunde/rechnungen': typeof KundeRechnungenRoute
  '/admin': typeof AdminIndexRoute
  '/kunde/neuer-vorgang/dropoff': typeof KundeNeuerVorgangDropoffRoute
  '/kunde/neuer-vorgang/pickup': typeof KundeNeuerVorgangPickupRoute
  '/kunde/neuer-vorgang': typeof KundeNeuerVorgangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kunde': typeof KundeRouteWithChildren
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/lieferscheine': typeof AdminLieferscheineRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/rechnungen': typeof AdminRechnungenRoute
  '/admin/sites': typeof AdminSitesRoute
  '/kunde/history': typeof KundeHistoryRoute
  '/kunde/lieferscheine': typeof KundeLieferscheineRoute
  '/kunde/neuer-vorgang': typeof KundeNeuerVorgangRouteWithChildren
  '/kunde/rechnungen': typeof KundeRechnungenRoute
  '/admin/': typeof AdminIndexRoute
  '/kunde/neuer-vorgang/dropoff': typeof KundeNeuerVorgangDropoffRoute
  '/kunde/neuer-vorgang/pickup': typeof KundeNeuerVorgangPickupRoute
  '/kunde/neuer-vorgang/': typeof KundeNeuerVorgangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kunde'
    | '/admin/companies'
    | '/admin/lieferscheine'
    | '/admin/products'
    | '/admin/rechnungen'
    | '/admin/sites'
    | '/kunde/history'
    | '/kunde/lieferscheine'
    | '/kunde/neuer-vorgang'
    | '/kunde/rechnungen'
    | '/admin/'
    | '/kunde/neuer-vorgang/dropoff'
    | '/kunde/neuer-vorgang/pickup'
    | '/kunde/neuer-vorgang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kunde'
    | '/admin/companies'
    | '/admin/lieferscheine'
    | '/admin/products'
    | '/admin/rechnungen'
    | '/admin/sites'
    | '/kunde/history'
    | '/kunde/lieferscheine'
    | '/kunde/rechnungen'
    | '/admin'
    | '/kunde/neuer-vorgang/dropoff'
    | '/kunde/neuer-vorgang/pickup'
    | '/kunde/neuer-vorgang'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kunde'
    | '/admin/companies'
    | '/admin/lieferscheine'
    | '/admin/products'
    | '/admin/rechnungen'
    | '/admin/sites'
    | '/kunde/history'
    | '/kunde/lieferscheine'
    | '/kunde/neuer-vorgang'
    | '/kunde/rechnungen'
    | '/admin/'
    | '/kunde/neuer-vorgang/dropoff'
    | '/kunde/neuer-vorgang/pickup'
    | '/kunde/neuer-vorgang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  KundeRoute: typeof KundeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kunde': {
      id: '/kunde'
      path: '/kunde'
      fullPath: '/kunde'
      preLoaderRoute: typeof KundeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/kunde/rechnungen': {
      id: '/kunde/rechnungen'
      path: '/rechnungen'
      fullPath: '/kunde/rechnungen'
      preLoaderRoute: typeof KundeRechnungenRouteImport
      parentRoute: typeof KundeRoute
    }
    '/kunde/neuer-vorgang': {
      id: '/kunde/neuer-vorgang'
      path: '/neuer-vorgang'
      fullPath: '/kunde/neuer-vorgang'
      preLoaderRoute: typeof KundeNeuerVorgangRouteImport
      parentRoute: typeof KundeRoute
    }
    '/kunde/lieferscheine': {
      id: '/kunde/lieferscheine'
      path: '/lieferscheine'
      fullPath: '/kunde/lieferscheine'
      preLoaderRoute: typeof KundeLieferscheineRouteImport
      parentRoute: typeof KundeRoute
    }
    '/kunde/history': {
      id: '/kunde/history'
      path: '/history'
      fullPath: '/kunde/history'
      preLoaderRoute: typeof KundeHistoryRouteImport
      parentRoute: typeof KundeRoute
    }
    '/admin/sites': {
      id: '/admin/sites'
      path: '/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AdminSitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rechnungen': {
      id: '/admin/rechnungen'
      path: '/rechnungen'
      fullPath: '/admin/rechnungen'
      preLoaderRoute: typeof AdminRechnungenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lieferscheine': {
      id: '/admin/lieferscheine'
      path: '/lieferscheine'
      fullPath: '/admin/lieferscheine'
      preLoaderRoute: typeof AdminLieferscheineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/kunde/neuer-vorgang/': {
      id: '/kunde/neuer-vorgang/'
      path: '/'
      fullPath: '/kunde/neuer-vorgang/'
      preLoaderRoute: typeof KundeNeuerVorgangIndexRouteImport
      parentRoute: typeof KundeNeuerVorgangRoute
    }
    '/kunde/neuer-vorgang/pickup': {
      id: '/kunde/neuer-vorgang/pickup'
      path: '/pickup'
      fullPath: '/kunde/neuer-vorgang/pickup'
      preLoaderRoute: typeof KundeNeuerVorgangPickupRouteImport
      parentRoute: typeof KundeNeuerVorgangRoute
    }
    '/kunde/neuer-vorgang/dropoff': {
      id: '/kunde/neuer-vorgang/dropoff'
      path: '/dropoff'
      fullPath: '/kunde/neuer-vorgang/dropoff'
      preLoaderRoute: typeof KundeNeuerVorgangDropoffRouteImport
      parentRoute: typeof KundeNeuerVorgangRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminLieferscheineRoute: typeof AdminLieferscheineRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRechnungenRoute: typeof AdminRechnungenRoute
  AdminSitesRoute: typeof AdminSitesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminLieferscheineRoute: AdminLieferscheineRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRechnungenRoute: AdminRechnungenRoute,
  AdminSitesRoute: AdminSitesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface KundeNeuerVorgangRouteChildren {
  KundeNeuerVorgangDropoffRoute: typeof KundeNeuerVorgangDropoffRoute
  KundeNeuerVorgangPickupRoute: typeof KundeNeuerVorgangPickupRoute
  KundeNeuerVorgangIndexRoute: typeof KundeNeuerVorgangIndexRoute
}

const KundeNeuerVorgangRouteChildren: KundeNeuerVorgangRouteChildren = {
  KundeNeuerVorgangDropoffRoute: KundeNeuerVorgangDropoffRoute,
  KundeNeuerVorgangPickupRoute: KundeNeuerVorgangPickupRoute,
  KundeNeuerVorgangIndexRoute: KundeNeuerVorgangIndexRoute,
}

const KundeNeuerVorgangRouteWithChildren =
  KundeNeuerVorgangRoute._addFileChildren(KundeNeuerVorgangRouteChildren)

interface KundeRouteChildren {
  KundeHistoryRoute: typeof KundeHistoryRoute
  KundeLieferscheineRoute: typeof KundeLieferscheineRoute
  KundeNeuerVorgangRoute: typeof KundeNeuerVorgangRouteWithChildren
  KundeRechnungenRoute: typeof KundeRechnungenRoute
}

const KundeRouteChildren: KundeRouteChildren = {
  KundeHistoryRoute: KundeHistoryRoute,
  KundeLieferscheineRoute: KundeLieferscheineRoute,
  KundeNeuerVorgangRoute: KundeNeuerVorgangRouteWithChildren,
  KundeRechnungenRoute: KundeRechnungenRoute,
}

const KundeRouteWithChildren = KundeRoute._addFileChildren(KundeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  KundeRoute: KundeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
